hw-10 ansible-1 with * task
Otus-DevOps-2021-11/anrad13_infra pull request #7
Opened 2022-01-19 21:27 UTC by anrad13

# Выполнено ДЗ №

 - [X] Основное ДЗ
 - [X] Задание со *

## В процессе сделано:
 - installed ansible. created ansible.cfg
 - created inventory, inventory.yml
 - created playbook clone
 - created inventory.json and inventory.sh for *task

## PR checklist
 - [X] Выставил label с номером домашнего задания
 - [X] Выставил label с темой домашнего задания

2022-01-20 19:29 UTC, mrgreyves requested changes
Здравствуйте!)
Проверил ваше дз
Вам стоит ознакомиться с результатами тестов
Нужно добавить пустые строки в конце файлов, выглядит как приключение на 5 минут
ДЗ возвращаю на доработку =)

2022-01-20 21:29 UTC, anrad13 commented
Здравствуйте Владимир. Прошу уточнить о каких файлах идет речь и какие тесты вы имеете ввиду.
Я могу видеть только что последний тест для последнего коммита был полностью успешен - https://github.com/Otus-DevOps-2021-11/anrad13_infra/runs/4887674483?check_suite_focus=true

2022-01-20 21:59 UTC, anrad13 commented
дополнительно выполнена ручная проверка всех файлов и найдено только несколько файлов без пустой строки на конце файла. Все файлы относились только к предыдущим ДЗ. Как я вижу гит мне показывает что "All checks have passed"

2022-01-21 16:18 UTC, mrgreyves approved these changes
Здравствуйте!)
Вот теперь все корректно =)

2022-01-21 16:23 UTC, merged